###
GET http://localhost:5000/api/members

###
GET http://localhost:5000/api/members/1


###
POST http://localhost:5000/api/members
Content-Type: application/json

{
    "name":"Samuel Smith",
    "email":"smith@gmail"
}

###
PUT http://localhost:5000/api/members/1
Content-Type: application/json

{
    "email":"john@yahoo.com"
}

###
DELETE http://localhost:5000/api/members/1



